// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package grpcapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SequenceLabelerClient is the client API for SequenceLabeler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SequenceLabelerClient interface {
	// Sends a request to /analyze.
	Analyze(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeReply, error)
}

type sequenceLabelerClient struct {
	cc grpc.ClientConnInterface
}

func NewSequenceLabelerClient(cc grpc.ClientConnInterface) SequenceLabelerClient {
	return &sequenceLabelerClient{cc}
}

func (c *sequenceLabelerClient) Analyze(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeReply, error) {
	out := new(AnalyzeReply)
	err := c.cc.Invoke(ctx, "/sequencelabeler.grpcapi.SequenceLabeler/Analyze", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SequenceLabelerServer is the server API for SequenceLabeler service.
// All implementations must embed UnimplementedSequenceLabelerServer
// for forward compatibility
type SequenceLabelerServer interface {
	// Sends a request to /analyze.
	Analyze(context.Context, *AnalyzeRequest) (*AnalyzeReply, error)
	mustEmbedUnimplementedSequenceLabelerServer()
}

// UnimplementedSequenceLabelerServer must be embedded to have forward compatible implementations.
type UnimplementedSequenceLabelerServer struct {
}

func (UnimplementedSequenceLabelerServer) Analyze(context.Context, *AnalyzeRequest) (*AnalyzeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Analyze not implemented")
}
func (UnimplementedSequenceLabelerServer) mustEmbedUnimplementedSequenceLabelerServer() {}

// UnsafeSequenceLabelerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SequenceLabelerServer will
// result in compilation errors.
type UnsafeSequenceLabelerServer interface {
	mustEmbedUnimplementedSequenceLabelerServer()
}

func RegisterSequenceLabelerServer(s grpc.ServiceRegistrar, srv SequenceLabelerServer) {
	s.RegisterService(&SequenceLabeler_ServiceDesc, srv)
}

func _SequenceLabeler_Analyze_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SequenceLabelerServer).Analyze(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sequencelabeler.grpcapi.SequenceLabeler/Analyze",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SequenceLabelerServer).Analyze(ctx, req.(*AnalyzeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SequenceLabeler_ServiceDesc is the grpc.ServiceDesc for SequenceLabeler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SequenceLabeler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sequencelabeler.grpcapi.SequenceLabeler",
	HandlerType: (*SequenceLabelerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Analyze",
			Handler:    _SequenceLabeler_Analyze_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sequencelabeler.proto",
}
