// Code generated by command: go run add_asm.go -out ../../matfuncs/add_amd64.s -stubs ../../matfuncs/add_amd64_stubs.go -pkg matfuncs. DO NOT EDIT.

//go:build amd64 && gc && !purego

package matfuncs

// AddAVX32 adds x1 and x2 element-wise, storing the result in y (32 bits, AVX required).
//
//go:noescape
func AddAVX32(x1 []float32, x2 []float32, y []float32)

// AddAVX64 adds x1 and x2 element-wise, storing the result in y (64 bits, AVX required).
//
//go:noescape
func AddAVX64(x1 []float64, x2 []float64, y []float64)

// AddSSE32 adds x1 and x2 element-wise, storing the result in y (32 bits, SSE required).
//
//go:noescape
func AddSSE32(x1 []float32, x2 []float32, y []float32)

// AddSSE64 adds x1 and x2 element-wise, storing the result in y (64 bits, SSE required).
//
//go:noescape
func AddSSE64(x1 []float64, x2 []float64, y []float64)
