// Code generated by command: go run addconst_asm.go -out ../../matfuncs/addconst_amd64.s -stubs ../../matfuncs/addconst_amd64_stubs.go -pkg matfuncs. DO NOT EDIT.

//go:build amd64 && gc && !purego

package matfuncs

// AddConstAVX32 adds a constant value c to each element of x, storing the result in y (32 bits, AVX required).
//
//go:noescape
func AddConstAVX32(c float32, x []float32, y []float32)

// AddConstAVX64 adds a constant value c to each element of x, storing the result in y (64 bits, AVX required).
//
//go:noescape
func AddConstAVX64(c float64, x []float64, y []float64)

// AddConstSSE32 adds a constant value c to each element of x, storing the result in y (32 bits, SSE required).
//
//go:noescape
func AddConstSSE32(c float32, x []float32, y []float32)

// AddConstSSE64 adds a constant value c to each element of x, storing the result in y (64 bits, SSE required).
//
//go:noescape
func AddConstSSE64(c float64, x []float64, y []float64)
