// Code generated by command: go run log_asm.go -out ../../matfuncs/log_amd64.s -stubs ../../matfuncs/log_amd64_stubs.go -pkg matfuncs. DO NOT EDIT.

//go:build amd64 && gc && !purego

package matfuncs

// LogAVX32 computes the natural logarithm of each element of x, storing the result in y (32 bits, AVX2 required).
//
//go:noescape
func LogAVX32(x []float32, y []float32)

// LogSSE32 computes the natural logarithm of each element of x, storing the result in y (32 bits, SSE required).
//
//go:noescape
func LogSSE32(x []float32, y []float32)
