// Code generated by command: go run sub_asm.go -out ../../matfuncs/sub_amd64.s -stubs ../../matfuncs/sub_amd64_stubs.go -pkg matfuncs. DO NOT EDIT.

//go:build amd64 && gc && !purego

package matfuncs

// SubAVX32 subtracts x2 from x1, element-wise, storing the result in y (32 bits, AVX required).
//
//go:noescape
func SubAVX32(x1 []float32, x2 []float32, y []float32)

// SubAVX64 subtracts x2 from x1, element-wise, storing the result in y (64 bits, AVX required).
//
//go:noescape
func SubAVX64(x1 []float64, x2 []float64, y []float64)

// SubSSE32 subtracts x2 from x1, element-wise, storing the result in y (32 bits, SSE required).
//
//go:noescape
func SubSSE32(x1 []float32, x2 []float32, y []float32)

// SubSSE64 subtracts x2 from x1, element-wise, storing the result in y (64 bits, SSE required).
//
//go:noescape
func SubSSE64(x1 []float64, x2 []float64, y []float64)
